name: example_code_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  source_gen: ^1.4.0
  analyzer: ^6.0.0
  http_mock_adapter: ^0.6.1
  dio: ^5.9.0

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^3.0.0
  test: ^1.24.0
