import 'package:build/build.dart';
import 'package:example_code_generator/src/example_code_generator.dart';
import 'package:source_gen/source_gen.dart';

Builder myBuilder(BuilderOptions options) {
  return PartBuilder(
    <Generator>[
      // MyGenerator(),
      // MockApiGenerator(),
      SoloMockApiGenerator()
    ],
    '.g.dart',
    header: '''
 // GENERATED BY STARTED
 ''',
  );
}