// GENERATED BY STARTED

part of 'example.dart';

// **************************************************************************
// MyGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
extension RunX on Run {
  void hello() => print("Hello from generator for test!");
}
